"""Generate app/src/lib/geo-centroids.ts (ISO alpha-2 -> [lon, lat]) from a Plotly geo topojson.

Usage: uv run --with pycountry python scripts/gen_geo_centroids.py <world_50m.json>
Source file: https://cdn.plot.ly/un/world_50m.json (country features carry `ct` = [lon, lat]).
The 50m file is used because the vendored 110m map omits small territories (HK, SG).
"""

import json
import sys
from pathlib import Path

import pycountry


def main() -> int:
    topo = json.loads(Path(sys.argv[1]).read_text())
    out: dict[str, tuple[float, float]] = {}
    for g in topo["objects"]["countries"]["geometries"]:
        a3, ct = g.get("id"), (g.get("properties") or {}).get("ct")
        c = pycountry.countries.get(alpha_3=a3) if a3 else None
        if c and ct:
            out[c.alpha_2] = (ct[0], ct[1])
    lines = [
        "// Generated by scripts/gen_geo_centroids.py from Plotly geo assets world_50m.json (feature `ct`).",
        "// ISO 3166-1 alpha-2 -> [longitude, latitude] in degrees. Do not edit by hand.",
        "export const CENTROIDS: Record<string, [number, number]> = {",
    ]
    lines += [f"\t{k}: [{v[0]}, {v[1]}]," for k, v in sorted(out.items())]
    lines.append("};")
    Path("app/src/lib/geo-centroids.ts").write_text("\n".join(lines) + "\n")
    print(f"{len(out)} centroids")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
